resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:0fc66356a9b861910bd9e9e0aaee4657e33e1d794c99891701c9bc5620e3ec78
  name: controller
  newName: registry.redhat.io/rhtas/rhtas-rhel9-operator
